export { default as analysis} from './analysis'
export { default as login} from './login'
export { default as main} from './main'
export { default as simul} from './simul'
export { default as table} from './table'
export { default as user} from './user'